const actions = {
  //BEHAVIOUR ACTION SAGAS
  BOOTSTRAP: 'BOOTSTRAP',
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  //COMMON ACTION SAGAS
  INCREMENT_REQUEST: 'INCREMENT_REQUEST',
  DECREMENT_REQUEST: 'DECREMENT_REQUEST',
};

export default actions;
